# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=25)),
                ('inv', models.CharField(max_length=20)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField()),
                ('broken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=140, null=True)),
                ('crash_date', models.DateField()),
                ('send_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('comment', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipments')),
            ],
        ),
    ]
