# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipments',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='inv',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='sn',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='repairing',
            name='company',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='repairing',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Repairing'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.ManyToManyField(to='equipments.Equipments'),
        ),
    ]
