# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20171026_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
    ]
